refactor to use async/await when it needed only
BCDevOps/nr-pipeline-ext pull request #100
Opened 2020-05-14 18:57 UTC by vesalink

2020-05-15 16:13 UTC, mbystedt requested changes
Let's have a session discussing the changes.

2020-05-21 22:24 UTC, mbystedt commented on lib/Jira.js
> +            return this.getJiraClient().issue.getIssue({ issueKey: issueKey })
Nice change!

2020-05-21 22:32 UTC, mbystedt commented on lib/dbBackupRecovery.js
> +;(function() {
Maybe remove the function()?

2020-05-21 22:37 UTC, mbystedt submitted a review, later dismissed
Looking good. The only things I saw was that lib/dbBackupRecovery.js is unnecessarily wrapping the code in a function.

2020-05-21 23:26 UTC, vesalink commented
> Looking good. The only things I saw was that lib/dbBackupRecovery.js is unnecessarily wrapping the code in a function.
done

2020-05-27 17:12 UTC, mbystedt approved these changes

2020-05-27 18:15 UTC, merged